### ISSUE TITLE
Update eid install page for Linux

### ISSUE THREAD

**Issue by galgalesh** [Fedict/eid-mw#11]
Hi

The [eid install page for Linux](http://eid.belgium.be/en/using_your_eid/installing_the_eid_software/linux) is quite difficult to understand at the moment. I'd like to propose some changes for it. Is there anyone I can contact about this?

Kind regards
Merlijn Sebrechts

**Comment by yoe** [comment]
Comments are always welcome. Go right ahead :)

**Comment by yoe** [comment]
No comments seem to be forthcoming, so closing this issue.
