### ISSUE TITLE
BEID_FIELD_TAG_ID_BasicKeyHash

### ISSUE THREAD

**Issue by dogguts** [Fedict/eid-mw#114]
In [cardcomm/pkcs11/src/beid_p11.h (line 77)](https://github.com/Fedict/eid-mw/blob/41f812afc6ef438ef948acde076c576e864b3841/cardcomm/pkcs11/src/beid_p11.h#L77)
```cpp
...
#define BEID_FIELD_TAG_ID_RegionalFileNumber		0x19
#define BEID_FIELD_TAG_ID_BasicKeyHash			0x20
...
```
**BEID_FIELD_TAG_ID_BasicKeyHash** should be **0x1A**;
 - according to [ID_ADRESSE_File_applet1_8_v1.pdf ](https://github.com/Fedict/eid-mw/blob/master/doc/sdk/documentation/Applet%201.8%20eID%20Cards/ID_ADRESSE_File_applet1_8_v1.pdf)
 - and since 0x1A follows on 0x19 in hex 

(from commit https://github.com/Fedict/eid-mw/commit/c965cc001d4c2eeed89f3391967513e3dfadcdda on a monday morning :wink: )

**Comment by Frederikus** [comment]
Thank you for reporting, updated it in the code

**Comment by dogguts** [comment]
thx
