### ISSUE TITLE
./configure and more files missing in repos.

### ISSUE THREAD

**Issue by linuxandos2** [Fedict/eid-mw#125]
Downloaded the zipfile.
Gentoo linux
Did a ./configure : command not found
Thanks
Marc

**Comment by yoe** [comment]
You didn't [follow the instructions](https://github.com/Fedict/eid-mw#code-from-git-repository), so then this isn't expected to work.

If you want to build from a git checkout (or from the github zip downloads, which is essentially the same thing) you have a few more extra steps to perform.
