### ISSUE TITLE
Wrong URL's in Fedora repo-files

### ISSUE THREAD

**Issue by jovandeginste** [Fedict/eid-mw#146]
The website for this is <https://eid.belgium.be/en/linux-eid-software-installation>

It suggests to install [this rpm](https://eid.belgium.be/sites/default/files/software/eid-archive-fedora-2016-2.noarch.rpm), which provides (ao.) `/etc/yum.repos.d/eid-archive.repo`. This file contains:

```ini
[beid-release]
name=Belgian eID package archive
baseurl=http://files.eid.belgium.be/rpm/fedora/$releasever
        http://files2.eid.belgium.be/rpm/fedora/$releasever
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-BEID-RELEASE
enabled=1
```
a) `http://files.eid.belgium.be/rpm/fedora/$releasever` does not work, it seems to work when using `https` instead
b) neither `http://files2.eid.belgium.be/rpm/fedora/$releasever` nor `https://files2.eid.belgium.be/rpm/fedora/$releasever` work
  The first one, probably same problem as a), the second one because TLS first (invalid cert), and then it says server is under maintenance...

The same issue (http -> https) is probably needed for the other repo's in the same file.

So, please fix the urls :) thanks!

**Comment by yoe** [comment]
The URLs are not wrong, but there is a technical issue (which we are in the process of trying to fix) that means currently it doesn't work.

That's being tracked in the other issue, so closing this one.
