### ISSUE TITLE
Installing on Fedora 34 fails - Unable to download metadata

### ISSUE THREAD

**Issue by ScrambleTheRamble** [Fedict/eid-mw#147]
Hi, 

I installled the eid rpm package on my Fedora 34 install but I can't install eid-viewer or eid-mw, seems to be an issue with the repository

`Error: Failed to download metadata for repo 'beid-release': repomd.xml parser error: Element <repomd> was not found - Bad repomd file
`

**Comment by yoe** [comment]
This is #143, it is being worked on.

**Comment by liedekef** [comment]
Why is this linked to #143 ? This is a fedora issue where the repodata xml file is invalid (it is clearly not an xml file), not something about http and certificates ...

**Comment by yoe** [comment]
No, this is not a fedora-specific issue. All content on files.eid.belgium.be is being replaced by some security service running in front of it if you use http (unless and until you open it in a browser once, at which point it will work for a while without a browser). That includes the repodata.xml file, but a lot more too.

This is being worked on at highest priority, but it is taking longer than expected. Please bear with us as we get this sorted.

**Comment by liedekef** [comment]
Weird: I accessed the repodata.xml file via a browser (firefox on fedora) and it still contains wrong data (no xml at all). But I'll be patient :-)
