### ISSUE TITLE
Can't connect with my eID

### ISSUE THREAD

**Issue by stemy2** [Fedict/eid-mw#152]
Hello,

Every time i try to connect with my eID, i get the following error:

```
Échec de la connexion sécurisée

Une erreur est survenue pendant une connexion à certif.iamfas.belgium.be. Le pair signale un échec de la vérification de signature ou de l’échange de clés.

Code d’erreur : SSL_ERROR_DECRYPT_ERROR_ALERT

    La page que vous essayez de consulter ne peut pas être affichée car l’authenticité des données reçues ne peut être vérifiée.
    Veuillez contacter les propriétaires du site web pour les informer de ce problème.
```

**Comment by yoe** [comment]
For this type of issue, please contact the BOSA servicedesk through https://eid.belgium.b/fr/contact, as the problem here is not necessarily a bug in the eid-mw software. The servicedesk will be happy to help you resolve the issue.

Thanks for your understanding,
