### ISSUE TITLE
Unknown label with latest ID cards

### ISSUE THREAD

**Issue by maxux** [Fedict/eid-mw#159]
I have a recent new ID card and when trying to read data with `eid-viewer API`, everything works, but I have 3 unknown labels:
```
E: unknown label: perso_versions
E: unknown label: tokeninfo_elec_perso_version
E: unknown label: tokeninfo_elec_perso_int_version
```

Field `perso_versions` contains 4 bytes, `tokeninfo_elec_perso_version` and `tokeninfo_elec_perso_int_version` contains only 1 byte on my card. I assume they are binary and not string.

**Comment by Frederikus** [comment]
Thanks for noticing, we'll ad them to the list.

They are binary indeed, you can find more info about them here: https://github.com/Fedict/eid-mw/blob/master/doc/sdk/documentation/Applet%201.8%20eID%20Cards/Belgian%20Electronic%20Identity%20Card%20content%20v5_4.pdf
(paragraph 5.3.1 EF(Tokeninfo)).

The perso_versions contains the 4 bytes, the other just 1 of the 4 bytes
