### ISSUE TITLE
Please provide packages for Fedora 36

### ISSUE THREAD

**Issue by ScrambleTheRamble** [Fedict/eid-mw#169]
Fedora 36 has been released, would it be possible to provide packages for Fedora 36?

**Comment by yoe** [comment]
You mean like ae2eb3d9b727b32348b2c71a932eee7b00450e6e and 7415035274ca7ff547e219b864a9af7f73e962a5 ?

**Comment by yoe** [comment]
You mean like ae2eb3d9b727b32348b2c71a932eee7b00450e6e and 4d47a4544b5683c02e1f0a4f5a84a850bfe32a4f ?

**Comment by ScrambleTheRamble** [comment]
Nice! So I guess these will pop up in the eid.belgium.be repo in the coming days or are there any other blockers?

**Comment by yoe** [comment]
testing, etc. But yeah, that's the plan.

**Comment by yoe** [comment]
Forgot about this issue, but Firefox 36 packages have been available for a while now.
