### ISSUE TITLE
Broken links in the main Wiki page

### ISSUE THREAD

**Issue by btlogy** [Fedict/eid-mw#18]
Most of the links look broken to me:

http://eid.belgium.be/nl/Hoe_installeer_je_de_eID/
http://eid-mw.googlecode.com/files/sdk40_1306.zip
http://www.rsa.com/rsalabs/node.asp?id=2133
https://code.google.com/p/eid-mw/source/browse/#svn%2Ftrunk%2Fdoc%2Fsdk%2Fexamples

**Comment by yoe** [comment]
Fixed. Thanks for the report!
