### ISSUE TITLE
Get separate firstnames

### ISSUE THREAD

**Issue by kristofvanwoensel** [Fedict/eid-mw#181]
I'm using the C# example to retrieve the eid data.

The label to get the firstname of the owner is "firstnames". 
Is there a way to retrieve the separate firstnames (firstname1, firstname2 and firstname3)?

Since this information is combined, it can't be seperated again with certainty that the names are correct.

**Comment by yoe** [comment]
Unfortunately not, as that is how the data is written on the card.
