### ISSUE TITLE
.net Sign example dosn't work with 1.8 card

### ISSUE THREAD

**Issue by KamiRaiden** [Fedict/eid-mw#184]
Hi, 

I'm currently using your .net code shown in the example.
https://github.com/Fedict/eid-mw/blob/9daa1d69bd97f9102ce66e89e22e38e618605816/doc/sdk/examples/CS/EidSamples/Sign.cs

With the introduction of the new eid 1.8, it doesn't seem to work anymore.

The line 80: P11Object[] privatekeys = session.FindObjects(1) as P11Object[];
return with an 1.8 card a null value in privatekeys[0].

Is there an other way to retrieve the PrivateKey object?
Or an other way to sign data?

Best regards,

**Comment by KamiRaiden** [comment]
Bonjour,

Auriez-vous une piste à ce propos? 
Je suis développeur à l'ONEM et nous utilisons ce code dans une de nos applications en productions et nous sommes bloqués.


Bien à vous

**Comment by Frederikus** [comment]
Hello,

Not sure if you are part of the same team that reported the issue on the dev mailing list, but could you check the version of the net.pkcs#11? It should be version 1.1.8494.15641 at least

**Comment by KamiRaiden** [comment]
Yes, I am.

I should have close the issue here, sorry that I forgot.

Have a nice day.
