### ISSUE TITLE
Multi-nationality EID XML sample

### ISSUE THREAD

**Issue by jeroenmaes** [Fedict/eid-mw#187]
The [eid XSD](https://github.com/Fedict/eid-mw/blob/f6103be50ee87e08620aba51c49d97bb9ff77001/plugins_tools/eid-viewer/xml/eidv4.xsd) only specifies a single field for nationality (min/max occurs 1). 
What happens when a person has dual or multi-nationality?

- Are all nationalities stored as a single string with some sort of delimiter? 
- Is only the first nationality stored on the eid?

**Comment by yoe** [comment]
The card can only hold one nationality (as per tag 0A of the "ID file", which is documented on page 3 of [the file format document](https://github.com/Fedict/eid-mw/blob/master/doc/sdk/documentation/Applet%201.8%20eID%20Cards/ID_ADRESSE_File_applet1_8_v4.pdf). As such, the viewer only stores one nationality, too.

Which nationality? I have no clue how this is decided; the national register makes that determination. You should contact them; you can find their contact information on [their website](https://www.ibz.rrn.fgov.be/nl/identiteitsdocumenten/eid/).
