### ISSUE TITLE
EID viewer working but CSAM does not detected the id card

### ISSUE THREAD

**Issue by karelstriegel** [Fedict/eid-mw#19]
First I've installed the eid viewer software for mac, I can read my id card, works perfectly, but when I then surf to the website where I need to authenticate myself I get the following error msg.
This happens on chrome and on safari. + I've just installed the latest software of the eid viewer (4.1.18)

![image](https://cloud.githubusercontent.com/assets/6882032/20002268/5d268dd4-a280-11e6-9be9-cf76384b398b.png)

**Comment by yoe** [comment]
For support issues, please find the correct support channel through the eID website:

http://eid.belgium.be/en/available_eid_applications/need_help

This bug tracker is not the appropriate place for getting that kind of support.
