### ISSUE TITLE
broken on firefox-esr

### ISSUE THREAD

**Issue by pirate486743186** [Fedict/eid-mw#208]
I'm in debian 12. Works fine in the viewer and chromium. With firefox-esr (115.12.0esr-1~deb12u1) it seams that it can't connect to the reader.

**Comment by yoe** [comment]
It works on my Debian installation. Something is clearly not set up correctly, but it's not possible for us to figure out what with the information given.

Could you please contact the BOSA support desk? They will be happy to help you out.

You can do this via https://eid.belgium.be/en/contact
