### ISSUE TITLE
ChromeOS port

### ISSUE THREAD

**Issue by LeGrosWinnie** [Fedict/eid-mw#213]
Hello,

On a ChromeBook there are 2 extensions working for some websites.
But main website like TaxOnWeb etc. (the old gui with the CSAM button) does not work.
Is there a way to build the code on a ChromeBook computer ?
There is an embeded Linux on cheomebooks (you can even run Linux Firefox etc.) but eID does not work even if it said it is installed (even on Linux env with all the command line done correctly using a DEB package etc.).

For the "build your own version" : a zip file with all dependencies would have been nice instead of : install that, install this, this one is required in this case (not even clear I think).
At the time of Maven project etc. doing such things by hand... is crazy...

I mean "After that it's just:"... yeah of course... After hours of settings up the env "it's just a command line"...

I even tried on a virtual Ubuntu, Firefox plugin does not even detect eID is installed... Even if the package manager say so. And it does not work of course (card reader detected and allowed to the VM).

Honnestly, this kind of stuff should have been done by government if it forces people to log in with an ID card...
ChromeBooks exist since 10 years now... Android more than that (and not compatible neither...).
And for real Linux I don't see why it failed on my VM.

Thanks.

**Comment by yoe** [comment]
This is handled by #75, so closing this in favor of that one.

Yes, it is theoretically possible to install the eid software in a chroot, but that is not officially supported by Google, and therefore also not by us.
