### ISSUE TITLE
Hello world with Visual Studio 2015 not working.

### ISSUE THREAD

**Issue by shamun** [Fedict/eid-mw#23]
I just git clone and then using Visual Studio 2015 did build/compile. On first attempt it failed. Then i did some scripts execute after that the build was success.

But when i now go to test folder i dont see any sample. Is there any sample to make sure my build / compile working?

**Comment by shamun** [comment]
Build failed:

![](http://i.imgur.com/DFiJY5l.png)

Even the DLL is in reference:

![image](https://cloud.githubusercontent.com/assets/107349/22702905/94f7ff86-ed62-11e6-9766-01c405cbe541.png)

**Comment by shamun** [comment]
Retried but still same.

![image](https://cloud.githubusercontent.com/assets/107349/22703247/c61cb858-ed63-11e6-8100-bc75563f3a97.png)

![image](https://cloud.githubusercontent.com/assets/107349/22703255/ce380f74-ed63-11e6-80d7-b02ba3d43791.png)

**Comment by shamun** [comment]
C code worked but not all, C# sample failed badly. Please update so that we can clone and retest.

![image](https://cloud.githubusercontent.com/assets/107349/22703734/6ef3945a-ed65-11e6-8795-ac64aed6ad1c.png)

**Comment by Frederikus** [comment]
Hello Shamun,

Thank you for your feedback, we will remove the app.config file.

What is the path of the net.pkcs11 library that is being referenced in your
project?
Could it be that you are trying to link the 64-bit version of
net.pkcs11.dll into a 32-bit application?

Wkr,
 Frederik

**Comment by Frederikus** [comment]
Looking at your second screenshot, I see its the 32-bit version and your
project is any-cpu, so on a 64-bit system, you will not be able to load the
32-bit version of the net.pkcs11.dll

**Comment by shamun** [comment]
I was unable to resolve it with C#. it keeps failing in my end. but the C code is working, so i will be using the C code.
