### ISSUE TITLE
Objective-C and Cordova?

### ISSUE THREAD

**Issue by shamun** [Fedict/eid-mw#28]
I am writing an app in Objective-C for iOS and iWatch also another app for Java. So that using iPhone, Android or iWatch one can do: taxonweb.be  quickly

How do i proceed? (can we build one Cordova plugin? so that its easy for all the iOS, Android programmers to access eID )

Please advise.

**Comment by yoe** [comment]
The eID middleware requires the PC/SC API to be able to talk to the eID card. Unfortunately, when last I checked, neither Android nor iOS provide that API. Additionally, at least in Android we found no way to hook into the central certificate store and add additional certificates from, e.g., an external smart card reader; I did not check this on iOS.

Given all of the above, currently our middleware is not supported on either of the two platforms, unfortunately. Given that it is fully open source, patches are welcome; but I'm afraid that for now, you just can't do this.

Having said that, I am aware of certain third-party solutions that do allow reading the eID from mobile platforms. However, these solutions are limited in that they only work with particular hardware and software, specifically designed for that platform. As a government body, it is not possible for us to support such solutions, although we have no reason to assume they won't work.
