### ISSUE TITLE
Programmatiion pour IOS

### ISSUE THREAD

**Issue by Alama32** [Fedict/eid-mw#3]
Hello, can you use your API for IOS? It's to make an app for iPad via XCODE you sample code? I just need minimums identifications, such  name, address and picture. Thank you.

Bonjour, peut-on utiliser votre API pour IOS? Dans le but de faire une app pour IPAD via XCODE avez-vous un exemple de code? j'ai juste besoin des identifications minimums, comme le nom, prénom, adresse et photo. Merci.

**Comment by yoe** [comment]
This was asked (and replied to) on [the mailinglist](https://groups.google.com/forum/#!topic/eid-middleware-dev/QtYAC3-XbZ8), so closing this issue here.
