### ISSUE TITLE
Warning pop up

### ISSUE THREAD

**Issue by armandomusto** [Fedict/eid-mw#39]
Hi,
I integrated the eID Viewer into my .NET Desktop application, but when I initialize the reader this warning pop ups.  How is it possible to hide it?

Thanks.

![screenshot_2](https://user-images.githubusercontent.com/4960206/27958667-7ad43240-6324-11e7-95e3-91490ad0e364.png)

**Comment by yoe** [comment]
Upgrade to middleware v4.2; in that version, these messages have been removed.

**Comment by armandomusto** [comment]
Hi joy,
thanks for the fast answer.
Which dll do I need to update?

**Comment by yoe** [comment]
The update was done for the PKCS#11 module (i.e., beidpkcs11.dll), but don't just update that DLL by itself; it might interact badly with the other parts of the middleware that are already on your system. Instead, you should just install the newest version of the middleware for your operating system as you can download it from https://eid.belgium.be/
