### ISSUE TITLE
Typo on https://eid.belgium.be/en/installation-and-removal#7314

### ISSUE THREAD

**Issue by stroobandt** [Fedict/eid-mw#43]
There is a typo on all language versions of https://eid.belgium.be/en/installation-and-removal#7314

    modutil -dbdir sql:.pki/nssdbi/ -list

should read:

    modutil -dbdir sql:.pki/nssdb/ -list

i.e. without the extra `i` at the end of `nssdb`.

**Comment by Frederikus** [comment]
Fixed it on all languages

Thanks for informing us
