### ISSUE TITLE
Outdated eid-archive version on English download page

### ISSUE THREAD

**Issue by stroobandt** [Fedict/eid-mw#45]
The page https://eid.belgium.be/en/linux-eid-software-installation offers to download the outdated version 'eid-archive_2017.3_all.deb' instead of the version `eid-archive_2017.4_all.deb` available on the equivalent [Dutch](https://eid.belgium.be/nl/linux-eid-software-installatie), French and German language pages.

**Comment by Frederikus** [comment]
Thanks again,

Updated it
