### ISSUE TITLE
Command formatting on https://eid.belgium.be/en/installation-and-removal#7310

### ISSUE THREAD

**Issue by stroobandt** [Fedict/eid-mw#47]
This affects the English language version of the page https://eid.belgium.be/en/installation-and-removal#7310

    sudo dpkg --add-architecture i386 sudo apt-get update

should read:

    sudo dpkg --add-architecture i386
    sudo apt-get update

The command formatting error does not appear on the Dutch language page.

**Comment by Frederikus** [comment]
Fixed them

Thanks for notifying
