### ISSUE TITLE
Register *.eid-extension to be opened by eID-Viewer

### ISSUE THREAD

**Issue by MichaelMedi** [Fedict/eid-mw#50]
Since the default extension for the 'Save As' function, it seems a nice feature to also open these files by default with the eID-viewer.

In Windows, the user is now presented with a 'Please select application'-screen.

**Comment by Frederikus** [comment]
Hello, sorry for the late reply, I've been on holiday.

The functionality is present in our future release of th eID Viewer (https://eid.belgium.be/nl/toekomstige-versies-van-de-eid-software-en-van-de-eid-viewer).
After you attach the .eid filetype with the eID Viewer, the eID Viewer will open the file when it launches
