### ISSUE TITLE
Google Chrome on macOS 10.13 (High Sierra): no certificates shown

### ISSUE THREAD

**Issue by Frederikus** [Fedict/eid-mw#55]
At the moment it is not possible to authenticate with your Belgian eID on macOS 10.13 using Google Chrome. This issue is know by the Google Chrome team and they are looking into it to fix it.

You can follow this issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=777805#c4

**Comment by koenvanloock** [comment]
I experienced this bug too, but was able to log in after a refresh. The second time I am prompted to fill in my pin code and everything works as intended.

**Comment by Frederikus** [comment]
Fixed, was due to padding bytes in cert file that confuse google chrome.
Fix will be in release 4.4.6 and above

**Comment by yoe** [comment]
It turns out that was not the actual issue, so reopening this bug.

**Comment by lionelbovy** [comment]
Hello,
I've approximately the same issue except that I get the following error message: ERR_BAD_SSL_CLIENT_AUTH_CERT (via http://test.eid.belgium.be/)
However, the certificates are valid when I check in the "Keychain Access" software. Moreover, it works when I use them via other browsers such as Safari & Firefox.

Besides, I've already contacted the help desk and followed the procedure they gave me but it still doesn't work. The answer I get most of the time is to install and use Firefox. Which works perfectly fine but I think it's unfortunate that one of the most used browsers, if not the most used, doesn't work.

- OS: macOS Catalina Version 10.15.2 (19C57)
- Browser: Chrome Version 79.0.3945.88 (Build officiel) (64 bits)
- eID Middleware: BEIDToken Version 4.4.14 (1)

![10-browser-error](https://user-images.githubusercontent.com/38806390/71924093-97326200-318e-11ea-8874-c9211424e88b.png)
![10-cert-1](https://user-images.githubusercontent.com/38806390/71924094-97caf880-318e-11ea-9280-83c52c97ec9b.png)
![10-cert-2](https://user-images.githubusercontent.com/38806390/71924096-97caf880-318e-11ea-94e5-fb0c21c60fc8.png)

**Comment by Frederikus** [comment]
It works with the latest eID cards.

But for older cards the following issue needs to be resolved: https://bugs.chromium.org/p/chromium/issues/detail?id=777805#c4
