### ISSUE TITLE
C# program closes after charArrayAtribute value = surname

### ISSUE THREAD

**Issue by ghost** [Fedict/eid-mw#56]
Dear

Everytime I launch the project(the c# expample) it gets stuck on charArrayAtribute value = surname.

Sincerly
![naamloos](https://user-images.githubusercontent.com/7889264/32610949-8b8b5846-c564-11e7-9c90-d51c56549c86.png)

**Comment by Frederikus** [comment]
Hello,

Can you explain me what this screenshot is about?
You want to wait there for console input (but the statement is placed after
the return of the function).

Can you show me exactly where the application is hanging?

Wkr,
 Frederik

**Comment by Frederikus** [comment]
Please re-open when you have feedback, but this doesn't look like an issue with our example code
