### ISSUE TITLE
TokenSession: PINByteOffset

### ISSUE THREAD

**Issue by fcorneli** [Fedict/eid-mw#80]
Should be 5 instead of 0 I guess...

**Comment by Frederikus** [comment]
Hello Frank,

I guess you are talking about userInteractionForSecurePINVerificationWithPINFormat:APDU:PINByteOffset:

https://developer.apple.com/documentation/cryptotokenkit/tksmartcard/1390289-userinteractionforsecurepinverif?language=objc

<QUOTE>
PINByteOffset
The offset, in bytes, within the Application Protocol Data Unit (APDU) field to mark a location of a PIN block for filling in the entered PIN.

Important

This parameter is not currently used. Pass 0.
<\QUOTE>

Did you notice an update about this function somewhere else?

**Comment by Frederikus** [comment]
Added a comment to the code, as this is confusing indeed

Thanks for checking our code
