### ISSUE TITLE
eID Viewer - Drag&Drop doesn't work (4.4.10) - Windows

### ISSUE THREAD

**Issue by MichaelMedi** [Fedict/eid-mw#83]
Dear,

We noticed that since version 4.4.10 of the eID-viewer, the drag&drop functionality doesn't work anymore in Windows 10. When I downgrade to version 4.4.9, it works again.
Upgrading to 4.4.12 doesn't solve the problem unfortunatly.

Was this function removed on purpose, or do we miss something?

**Comment by Frederikus** [comment]
Hello,

This function was not removed on purpose.
We will try to correct this as soon as possible.

**Comment by MichaelMedi** [comment]
Hello @Frederikus 

I can confirm the drag&drop is working again on Windows 10 in the new beta-release (4.4.14).

Thanks for the swift solution!

**Comment by Frederikus** [comment]
Hello Michael,

Thank you for verifying
