### ISSUE TITLE
Memory corruption readers_changed_real() @ gtkui.c

### ISSUE THREAD

**Issue by spukhaftefernwirkung** [Fedict/eid-mw#90]
The size calculated to store the items in readers_changed_real() @ gtkui.c is wrong:
 
```
	items = malloc(sizeof(GtkWidget*) * info->nreaders + 1);
	for(i=0; i<info->nreaders; i++) {
	[...]
	}
	items[info->nreaders] = NULL;
```
It should of course be : sizeof(GtkWidget*) * (info->nreaders + 1) otherwise this results in memory corruption.

**Comment by yoe** [comment]
Thanks, good catch. You're right, of course; fix committed.
