### ISSUE TITLE
Mac OSX "Validate Now" doesn't seem functional

### ISSUE THREAD

**Issue by dietercastel** [Fedict/eid-mw#96]
The validate now function doesn't seem to do anything. The log remains empty. Does that mean that the certificate is never validated at all?

**Comment by yoe** [comment]
The log may not show something unless you have it set to detail at least.If the validation fails, then you will get an appropriate error message.If the validation succeeds, then when you click on one of the certificates, the image to the left of the certificate data will contain a green check mark to signify that the validation has occurred and the certificates are valid.It is true that the interface does not immediately show that the certificates are valid until you do that.

**Comment by dietercastel** [comment]
I'll see how that goes with "Detail" level log when I'm near a smart card reader again.

**Comment by yoe** [comment]
I've just updated the UI (on master only, for now) to also show the certificate image in the outlineView. If that doesn't seem to confusing, we'll backport that to the v4.4 branch for the next release.

That should take care of this issue.

**Comment by dietercastel** [comment]
I managed to find time to get you the requested logs. Still the same thing no validation happening. I also noticed that you now serve a previous version v.4.4.14. 

<img width="417" alt="Screenshot 2019-11-25 at 13 47 01" src="https://user-images.githubusercontent.com/2487783/69542029-dc0d8b00-0f8a-11ea-8008-6a9b063fd7e4.png">

Note that I'm still using the version I downloaded when reporting this bug that is **v.4.4.16**
<img width="277" alt="Screenshot 2019-11-25 at 13 45 41" src="https://user-images.githubusercontent.com/2487783/69542030-dc0d8b00-0f8a-11ea-870f-7a20a1c88d3f.png">
<img width="455" alt="Screenshot 2019-11-25 at 13 43 51" src="https://user-images.githubusercontent.com/2487783/69542082-f3e50f00-0f8a-11ea-98b9-ba8ec8d0d473.png">

```
D: Handling state transition for event TOKEN_INSERTED
D: Leaving state READY
D: Leaving state NO_TOKEN
D: Entering state TOKEN (target)
D: Entering state TOKEN_ID (child)
D: found data for label ATR
D: found data for label CARD_DATA
D: found data for label carddata_serialnumber
D: found data for label carddata_comp_code
D: found data for label carddata_os_number
D: found data for label carddata_os_version
D: found data for label carddata_soft_mask_number
D: found data for label carddata_soft_mask_version
D: found data for label carddata_appl_version
D: found data for label carddata_glob_os_version
D: found data for label carddata_appl_int_version
D: found data for label carddata_pkcs1_support
D: found data for label carddata_key_exchange_version
D: found data for label carddata_appl_lifecycle
D: found data for label DATA_FILE
D: found data for label card_number
D: converting card_number
D: found data for label chip_number
D: converting chip_number
D: found data for label validity_begin_date
D: found data for label validity_end_date
D: found data for label issuing_municipality
D: found data for label national_number
D: converting national_number
D: found data for label surname
D: found data for label firstnames
D: found data for label first_letter_of_third_given_name
D: found data for label nationality
D: found data for label location_of_birth
D: found data for label date_of_birth
D: converting date_of_birth
D: found data for label gender
D: converting gender
D: found data for label nobility
D: found data for label document_type
D: converting document_type
D: found data for label special_status
D: converting special_status
D: found data for label photo_hash
D: found data for label ADDRESS_FILE
D: found data for label address_street_and_number
D: found data for label address_zip
D: found data for label address_municipality
D: found data for label PHOTO_FILE
D: found data for label CERT_RN_FILE
D: found data for label SIGN_DATA_FILE
D: found data for label SIGN_ADDRESS_FILE
D: Handling state transition for event READ_READY
D: Leaving state TOKEN_ID
D: found data for label Authentication
D: found data for label Signature
D: found data for label CA
D: found data for label Root
D: Handling state transition for event READ_READY
D: Leaving state TOKEN_CERTS
D: Entering state TOKEN_WAIT (target)
D: Entering state TOKEN_IDLE (child)
D: State transition for READ_READY complete
D: Entering state TOKEN_CERTS (target)
D: State transition detected, aborting handling of READ_READY
D: State transition detected, aborting handling of TOKEN_INSERTED
```

As you can see below, the validation does absolutely nothing. I think re-opening this issue is required.

<img width="455" alt="Screenshot 2019-11-25 at 13 43 51" src="https://user-images.githubusercontent.com/2487783/69542163-255dda80-0f8b-11ea-8f3f-22c03f682b77.png">

**Comment by yoe** [comment]
This was fixed, but the fixed version has not been released yet, and hence is not yet available for download.

The next release of a macOS version, when it happens, will have an icon in the tree view that shows the current certificate validity status. When certificates are successfully validated, either through the "Validate now" button or the "Always validate" checkbox, the certificate validity icon will be updated.

Also note that even in the version you're using, the certificate validity icon is available, but it is only shown when you select a certificate in the tree view; when validation has occurred, the icon will show a green check mark, and the "trust:" entry in the list will show that it is trusted, which is not the case before validation has happened.

**Comment by yoe** [comment]
A new version of the viewer with the fix for this issue has been released, and is available as a beta download from the official website now.
